// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250622165140_AddedAl")]
    partial class AddedAl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Anna",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kowalska"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Jan",
                            HireDate = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nowak"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Nursery", b =>
                {
                    b.Property<int>("NurseryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NurseryId"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NurseryId");

                    b.ToTable("Nurseries");

                    b.HasData(
                        new
                        {
                            NurseryId = 1,
                            EstablishedDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Green Forest"
                        },
                        new
                        {
                            NurseryId = 2,
                            EstablishedDate = new DateTime(2010, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mountain Trees"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Responsible", b =>
                {
                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BatchId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Responsibles");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            EmployeeId = 1,
                            Role = "Supervisor"
                        },
                        new
                        {
                            BatchId = 1,
                            EmployeeId = 2,
                            Role = "Planter"
                        },
                        new
                        {
                            BatchId = 2,
                            EmployeeId = 2,
                            Role = "Supervisor"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Seedling_Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("NurseryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SownDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("NurseryId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Seedling_Batches");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            NurseryId = 1,
                            Quantity = 100,
                            ReadyDate = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SownDate = new DateTime(2015, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpeciesId = 1
                        },
                        new
                        {
                            BatchId = 2,
                            NurseryId = 1,
                            Quantity = 200,
                            ReadyDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SownDate = new DateTime(2020, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpeciesId = 2
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Tree_Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"));

                    b.Property<int>("GrowthTimeInYears")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpeciesId");

                    b.ToTable("Tree_Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            GrowthTimeInYears = 5,
                            LatinName = "Quercus robur"
                        },
                        new
                        {
                            SpeciesId = 2,
                            GrowthTimeInYears = 3,
                            LatinName = "Pinus sylvestris"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Responsible", b =>
                {
                    b.HasOne("Kolokwium.Models.Seedling_Batch", "Batch")
                        .WithMany("Responsible")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Employee", "Employee")
                        .WithMany("Responsibilities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Kolokwium.Models.Seedling_Batch", b =>
                {
                    b.HasOne("Kolokwium.Models.Nursery", "Nursery")
                        .WithMany("SeedlingBatches")
                        .HasForeignKey("NurseryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Tree_Species", "Species")
                        .WithMany("Batches")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nursery");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Kolokwium.Models.Employee", b =>
                {
                    b.Navigation("Responsibilities");
                });

            modelBuilder.Entity("Kolokwium.Models.Nursery", b =>
                {
                    b.Navigation("SeedlingBatches");
                });

            modelBuilder.Entity("Kolokwium.Models.Seedling_Batch", b =>
                {
                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Kolokwium.Models.Tree_Species", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
